### ISSUE TITLE
'module' object is not callable

### ISSUE THREAD

**Issue by drhanlau** [chenjr0719/Facebook-Page-Crawler#2]
I got the followng error

```
Traceback (most recent call last):
  File "/Users/cherhan/anaconda/bin/facebook_page_crawler", line 11, in <module>
    load_entry_point('facebook-page-crawler', 'console_scripts', 'facebook_page_crawler')()
TypeError: 'module' object is not callable
```

**Comment by chenjr0719** [comment]
Sorry for late reply.
I fix setup.py please reinstall and try it again.

**Comment by marcelobazevedo** [comment]
I got the followng error

2018-03-13 15:39:46 - (FacebookPageCrawler)[INFO] - Initialize crawler
Traceback (most recent call last):
  File "/usr/local/bin/facebook_page_crawler", line 11, in <module>
    load_entry_point('facebook-page-crawler', 'console_scripts', 'facebook_page_crawler')()
  File "/home/administrador/Documentos/2018/cibernetica/Facebook-Page-Crawler-master/facebook_page_crawler/__main__.py", line 26, in main
    crawler.setConfig(**vars(args))
  File "/home/administrador/Documentos/2018/cibernetica/Facebook-Page-Crawler-master/facebook_page_crawler/facebook_page_crawler.py", line 52, in setConfig
    '%Y-%m-%d %H:%M:%S'
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'

**Comment by chenjr0719** [comment]
@marcelobazevedo 
Sorry for the really late reply...

`datetime.datetime.timestamp()` only work when **Python >= 3.3**
Consider using a newer version of Python, please
And your issue should be same with #4 , please follow that one
This issue should be close
