### ISSUE TITLE
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'

### ISSUE THREAD

**Issue by duan78** [chenjr0719/Facebook-Page-Crawler#4]
Hi,

I can't run the script, it prompt me this error : 
2018-05-07 05:37:17 - (FacebookPageCrawler)[INFO] - Initialize crawler
Traceback (most recent call last):
  File "/usr/local/bin/facebook_page_crawler", line 11, in <module>
    load_entry_point('facebook-page-crawler', 'console_scripts', 'facebook_page_crawler')()
  File "/root/Facebook-Page-Crawler/facebook_page_crawler/__main__.py", line 26, in main
    crawler.setConfig(**vars(args))
  File "/root/Facebook-Page-Crawler/facebook_page_crawler/facebook_page_crawler.py", line 52, in setConfig
    '%Y-%m-%d %H:%M:%S'
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'

Regards,

**Comment by chenjr0719** [comment]
Hi,

Can you tell me which version of Python you run this program?

duan78 <notifications@github.com> 於 2018年5月7日 週一 下午5:37寫道：

**Comment by chenjr0719** [comment]
Found something may help
https://stackoverflow.com/a/8778548
`datetime.datetime.timestamp()` only work when **Python >= 3.3**
Consider using a newer version of Python, please

**Comment by raadbintareaf** [comment]
my python is 3.6.2 and got the same error.
